
DEBUG = true               -- GENERIC DEBUGGING
--DEBUG_PARSER = true        -- OBJ_PARSE DEBUGGING
--DEBUG_NUMBER = true        -- OBJ_NUMBER DEBUGGING
--DEBUG_GATEWAY = true       -- OBJ_GATEWAY DEBUGGING
--DEBUG_DIALSTRING = true    -- OBJ_DIALSTRING DEBUGGING
--DEBUG_LOCATION = true      -- OBJ_LOCATION DEBUGGING
--DEBUG_ROUTE = true         -- OBJ_ROUTE DEBUGGING
DEBUG_DESTINATION = true   -- OBJ_DESTINATION DEBUGGING
