
DEBUG = true               -- GENERIC DEBUGGING
DEBUG_PARSER = true        -- OBJ_PARSE DEBUGGING
DEBUG_NUMBER = true        -- OBJ_NUMBER DEBUGGING
--DEBUG_GATEWAY = true       -- OBJ_GATEWAY DEBUGGING
DEBUG_DIALSTRING = true    -- OBJ_DIALSTRING DEBUGGING
DEBUG_LOCATION = true
DEBUG_EXTENSION = true
