
DEBUG = false               -- GENERIC DEBUGGING
DEBUG_PARSE = false         -- OBJ_PARSE DEBUGGING
DEBUG_NUMBER = false        -- OBJ_NUMBER DEBUGGING
DEBUG_GATEWAY = false       -- OBJ_GATEWAY DEBUGGING
DEBUG_DIALSTRING = false    -- OBJ_DIALSTRING DEBUGGING
DEBUG_LOCATION = false      -- OBJ_LOCATION DEBUGGING
DEBUG_ROUTE = false         -- OBJ_ROUTE DEBUGGING
DEBUG_DESTINATION = true    -- OBJ_DESTINATION DEBUGGING
